name: whitewax
favicon: null
layout_spectrum: 0.5397368629928678
typography_spectrum: 0.405185479670763
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5778785336297005
  lightness: 0.028248844668269157
  saturation: 0.39863873226568103
  rhythmicContrast: 0.4124113309662789
purpose: []
